### ISSUE TITLE
Help wanted: per-project code coverage

### ISSUE THREAD

**Issue by spautz** [spautz/react-hibernate#10]
The repo generates code coverage reports both for the individual libraries and for the repo as a whole. At the moment it only seems possible to present a badge/shield for the repo as a whole, but I'd like to show code coverage for the individual libraries.

This suggests it's not yet feasible: https://github.com/lemurheavy/coveralls-public/issues/1174

No other open-source projects I've found have per-project code coverage numbers, but if anybody knows of one that does then I'd love to see it.

**Comment by ionicsolutions** [comment]
Hi, I came across your question when searching for a solution to this issue and I have found a workaround, so I thought I'd leave it here as I'm probably not the only one who finds their way here.

I'm using the fact that coveralls.io allows to track the coverage per branch to generate badges for individual libraries/packages using GitHub Actions:

```yaml
name: Run tests with pytest
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    COVERALLS_FLAG_NAME: package
    REPORT_PACKAGE: ${{ github.ref == 'refs/heads/master' }}
run: |
    set -e
    cd ./to/the/package-root

    pip install -r requirements-test.txt
    pytest -v --cov=package tests/

    # when on master, pretend to be on branch x-cov-package
    $REPORT_PACKAGE && export GITHUB_REF="refs/heads/x-cov-package"
    $REPORT_PACKAGE && export GITHUB_HEAD_REF="x-cov-package"
    coveralls --service=github
```  

You need to permanently keep a branch `x-cov-package` for coveralls.io to keep the data and provide a badge at `https://coveralls.io/github/your-org/your-repo?branch=x-cov-package` (I named them `x-cov-*` to be able to identify and protect them from deletion.)

It's not an ideal solution, as it depends on the internals of the particular coveralls Python client, but it should be fairly stable and easy to port to other coveralls clients.

You can see the full setup in action at https://github.com/XAI-Demonstrator/xai-demonstrator.
